name: UnitiumPlugin2
version: '${project.version}'
main: fr.bouboule.unitiumplugin2.UnitiumPlugin2
depend: [dynmap]
commands:
  country:
    description: Command to manage country
    aliases:
      - pays
      - c
      - p
    permission: command.country
    permission-message: ยง4You do not have permission!
    usage: ยง4/<command> <subcommand>
  shop:
    description: Command to use shop
    permission: command.shop
    permission-message: ยง4You do not have permission!
    usage: ยง4/<command>
